// Bar 10 — Centralized site data
// Edit this file to update hours, contact info, menu, and events across the site.

const BAR10 = {
  name: "Bar 10",
  tagline: "Wyoming Bred. Craft Beer. Craft Cocktails. Artisan Pizza. Raising the Bar in County Ten.",
  address: {
    street: "114 S Broadway Ave",
    city: "Riverton",
    state: "WY",
    zip: "82501",
    full: "114 S Broadway Ave, Riverton, WY 82501",
  },
  phone: "(307) 856-2337",
  phoneHref: "tel:+13078562337",
  email: "bar10wyo@gmail.com",
  mapLink: "https://maps.google.com/?q=114+S+Broadway+Ave+Riverton+WY+82501",
  social: {
    facebook: "https://www.facebook.com/bar10wyo",
    instagram: "https://www.instagram.com/bar10wyo/",
  },
  hours: [
    { day: "Monday",    open: "4:00 PM", close: "11:00 PM" },
    { day: "Tuesday",   open: "4:00 PM", close: "11:00 PM" },
    { day: "Wednesday", open: "4:00 PM", close: "11:00 PM" },
    { day: "Thursday",  open: "4:00 PM", close: "11:00 PM" },
    { day: "Friday",    open: "4:00 PM", close: "12:00 AM" },
    { day: "Saturday",  open: "4:00 PM", close: "12:00 AM" },
    { day: "Sunday",    open: null,      close: null        },
  ],
  menu: {
    favoritesNote: "Bar Ten signatures — crowd-pleasing plates and house specialties.",
    favorites: [
      { name: "Chicken Pot Pie",     price: "$10.99", desc: "An all-American comfort food classic. Large, meaty chunks of juicy white chicken breast with sweet carrots and peas, covered in a buttery cream sauce." },
      { name: "Italian Slider",      price: "$11.99", desc: "Canadian bacon, pepperoni, mozzarella, lettuce, tomatoes, red onion, pepperoncini, and house dressing." },
      { name: "Meatball Sliders",    price: "$10.99", desc: "Traditional big plump meatballs, signature marinara, fresh basil, mozzarella, and shaved parmesan." },
      { name: "Cuban Slider",        price: "$11.99", desc: "Pulled pork/ham, mustard, Swiss, and deli pickle." },
      { name: "Whiskey BBQ Sliders", price: "$10.99", desc: "House pulled pork, caramelized onions, cheddar cheese, and our signature whiskey BBQ." },
      { name: "Pork Street Tacos",   price: "$11.99", desc: "House pulled pork, onions, cilantro, fresh jalapeños, and Bar Ten hot sauce." },
    ],
    pizzas: {
      crusts: "House crust, thin crust, flatbread, or 12\u2033 cauliflower crust.",
      items: [
        { name: "Thai Chicken",     price14: "$20.99", price7: "$11.99", desc: "Thai peanut sauce, chicken, peppers, red onion, topped with mint, basil, and cilantro." },
        { name: "Surf & Turf",      price14: "$24.99", price7: "$14.99", desc: "Chipotle cream, plump shrimp, bacon, red onion, tomatoes, and cheddar jack." },
        { name: "BBQ Pig",          price14: "$20.99", price7: "$11.99", desc: "Whiskey BBQ sauce, pulled pork, bacon, caramelized onions, and cheddar jack cheese." },
        { name: "The Greek",        price14: "$20.99", price7: "$11.99", desc: "Olive oil, gyro style lamb, red onion, tomatoes, goat cheese, Kalamata olives, cucumbers, and tzatziki drizzle." },
        { name: "Chipotle Chicken", price14: "$23.99", price7: "$12.99", desc: "Chipotle cream, chicken, red onion, jalapeños, corn, cheddar jack, topped with tortilla chips, cilantro, and chipotle raspberry drizzle." },
        { name: "Popo Agie",        price14: "$20.99", price7: "$11.99", desc: "White sauce, spinach, artichoke hearts, mushrooms, tomatoes, and mozzarella.", note: "Add chicken for $2." },
        { name: "Apple Jacked",     price14: "$20.99", price7: "$11.99", desc: "Olive oil, bacon, apples, blue cheese with a balsamic reduction." },
        { name: "Garlic Shrimp",    price14: "$23.99", price7: "$12.99", desc: "Butter wine sauce, shrimp, garlic, tomatoes, asiago, topped with green onions." },
        { name: "Sweet Heat",       price14: "$20.99", price7: "$11.99", desc: "Marinara, Italian sausage, chorizo, jalapeños, caramelized onions with Thai sweet chili." },
        { name: "County 10",        price14: "$20.99", price7: "$11.99", desc: "Marinara, pepperoni, bacon, ham, sausage, and mozzarella." },
        { name: "Sunshine Vine",    price14: "$20.99", price7: "$11.99", desc: "Marinara, spinach, cremini mushrooms, artichoke hearts, caramelized onions, tomatoes, garlic, goat cheese, and balsamic reduction." },
        { name: "Fig & Pig",        price14: "$20.99", price7: "$11.99", desc: "Olive oil, chorizo, dates, goat cheese, and spinach." },
        { name: "The Bar10der",     price14: "$17.99", price7: "$9.99",  desc: "Marinara, pepperoni, sausage, mushrooms, red onions, mozzarella, and shaved parmesan.", note: "Add green olives and red pepper flakes for the true BAR10DER experience." },
      ],
    },
    appetizers: [
      { name: "Meatballs",              price: "$9.99",  desc: "Three meatballs with house marinara, fresh basil, and grated parmesan." },
      { name: "Stuffed Jalapeños",      price: "$9.99",  desc: "In-house cheese stuffing topped with bacon and our whiskey BBQ." },
      { name: "Stuffed Mushrooms",      price: "$9.99",  desc: "In-house cheese stuffing with spicy Italian sausage and sweet soy." },
      { name: "Devils on Horseback",    price: "$10.99", desc: "Gorgonzola stuffed dates wrapped in bacon." },
      { name: "Artichoke Dip",          price: "$10.99", desc: "A Bar Ten signature, served with breadsticks." },
      { name: "Ronnie Stromboli",       price: "$10.99", desc: "Marinara, double pepperoni, mozzarella, and green onions." },
      { name: "Coastal Shrimp Cocktail",price: "$11.99", desc: "Six plump shrimp served with our in-house cocktail sauce." },
      { name: "Nachos",                 price: "$13.99", priceAlt: "Half Nachos — $8.99", desc: "Choice of chicken, pulled pork, or chorizo, black beans, red onion, jalapeños, tomatoes, chipotle cream, and cheddar/jack cheese." },
      { name: "Bacon Wrapped Shrimp",   price: "$13.99", desc: "Six plump shrimp served with sweet soy and garlic butter." },
      {
        name: "Ribs", label: "The Best in Fremont County!",
        tiers: [
          { size: "1/4 Rack", price: "$10.99" },
          { size: "1/2 Rack", price: "$15.99" },
          { size: "Full Rack", price: "$26.99" },
        ],
        desc: "Slow-cooked and then seasoned with your choice of signature whiskey BBQ, Asian, buffalo, or buffalo blue sauce.",
      },
      {
        name: "Cheese Board", price: "$13.99", note: "When available.",
        desc: "A selection of fine cheeses paired with dates, apples, Kosmo cherry peppers, spiced walnuts, and Kalamata olives.",
        cheeses: ["Grand Cru Reserve", "Smoked Fontina", "Sriracha Gouda", "Prairie Sunset"],
      },
    ],
    salads: {
      note: "All salads are made with Oregon spring mix.",
      items: [
        { name: "The House",           price: "$6.99",  desc: "House croutons, cucumbers, and tomatoes... your basic side salad!" },
        { name: "Pear & Gorgonzola",   price: "$10.99", desc: "Spiced walnuts, pears, and gorgonzola served with balsamic vinaigrette." },
        { name: "Chicken Bacon Ranch", price: "$12.99", desc: "Chicken, bacon, cucumber, red onion, tomatoes, cilantro, pepperoncini, and house croutons." },
        { name: "Asian",               price: "$12.99", desc: "Peppers, green onions, tomatoes, chicken, topped with La Choy fry noodles, cilantro, mint, served with Asian dressing." },
        { name: "BBQ Chicken",         price: "$13.99", desc: "Chicken, bacon, tortilla strips, black beans, corn, cilantro, tomatoes, cucumbers, served with Bar Ten BBQ and ranch dressing." },
        { name: "Greek",               price: "$10.99", desc: "Tomatoes, red onion, cucumbers, Kalamata olives, goat cheese, and Bar Ten balsamic vinaigrette.", note: "Add chicken for $2." },
        { name: "Italian Salad",       price: "$13.99", desc: "Chopped pepperoni, Canadian bacon, applewood bacon, olives, pepperoncinis, tomatoes, and mozzarella cheese served with Bar Ten balsamic vinaigrette." },
      ],
    },
    pastas: {
      note: "Traditional Italian Cuisine",
      items: [
        { name: "Mac & Cheese",   price: "$8.99",  desc: "Macaroni, parmesan cream sauce, cheddar, jack, and blue cheese.", note: "Add bacon for $1." },
        { name: "Meatball Penne", price: "$9.99",  desc: "Marinara, meatball, fresh basil, mozzarella, and fresh parmesan." },
        { name: "Shrimp Scampi",  price: "$11.99", desc: "Plump shrimp, garlic butter, green onions, fresh garlic, and shaved parmesan." },
      ],
    },
    buildYourOwn: {
      sizes: [
        { size: "14\u2033 Pizza",  basePrice: "$16.99", toppingPrice: "$1.50" },
        { size: "7\u2033 Pizza",   basePrice: "$8.99",  toppingPrice: "$0.75" },
      ],
      crusts: "House crust, thin crust, flatbread, or 12\u2033 cauliflower crust.",
      toppingNote: "Unlimited Toppings",
      categories: [
        { label: "Meat",    items: ["Pepperoni", "Spicy Italian Sausage", "Meatball", "Shrimp", "Bacon", "Pulled Pork", "Chicken", "Chorizo", "Lamb"] },
        { label: "Sauce",   items: ["Marinara", "BBQ", "Asian", "White Sauce", "Thai Peanut", "Buffalo", "Garlic Butter", "Chipotle Cream"] },
        { label: "Cheese",  items: ["Mozzarella", "Cheddar/Jack", "Goat Cheese", "Gorgonzola", "Shaved Parmesan", "Asiago"] },
        { label: "Veggies", items: ["Artichoke Hearts", "Pepperoncini", "Kalamata Olives", "Green Olives", "Black Olives", "Red Onion", "Corn", "Green Onion", "Caramelized Onion", "Jalape\u00f1os", "Mixed Bell Peppers", "Mushrooms", "Spinach", "Tomatoes", "Apples", "Dates", "Cilantro", "Basil", "Mint"] },
        { label: "Drizzle", items: ["Sweet Chili", "Balsamic Glaze", "Ranch", "Buffalo", "Sweet Soy", "BBQ"] },
      ],
    },
    desserts: {
      note: "Bartender Sundaes",
      items: [
        { name: "Grasshopper",    price: "$8.99", desc: "Cr\u00e8me de menthe and chocolate sauce over vanilla bean ice cream topped with whipped cream and a cherry." },
        { name: "My Name Is Mud", price: "$8.99", desc: "Kahl\u00faa, Bailey\u2019s, chocolate sauce over vanilla bean ice cream topped with whipped cream and a cherry." },
        { name: "Southern Cross", price: "$8.99", desc: "Old Weller bourbon and chocolate/caramel sauce over vanilla bean ice cream topped with spiced walnuts, whipped cream, and a cherry." },
      ],
      footer: "Ask your bartender for ideas.",
    },
    drinks: {
      note: "Full Bar \u00b7 Craft Cocktails \u00b7 Local & Craft Beer \u00b7 Wine \u00b7 Spirits",
      categories: [
        {
          label: "Dessert Martinis",
          items: [
            { name: "Cotton Candy",             desc: "Why go to a carnival when we have it right here." },
            { name: "Birthday Cake",             desc: "A must on your special day." },
            { name: "Gummy Bear",                desc: "Always a surprise at the bottom." },
            { name: "Reese\u2019s Peanut Butter Cup", desc: "All the richness of a peanut butter cup." },
            { name: "Appletini",                 desc: "Picked fresh from the tree." },
            { name: "Caramel Apple",             desc: "A sweet and sour experience." },
            { name: "Chocotini",                 desc: "For the chocolate lovers." },
            { name: "Dreamcycle",                desc: "Dream of orange and cream." },
            { name: "Key Lime Pie",              desc: "Best of both worlds." },
            { name: "Espresso Martini",          desc: "A lovely blend of vodka and coffee." },
            { name: "Mighty Joe Kong",           desc: "No monkeying around \u2014 straight up chocolate and banana flavors." },
            { name: "Raspberry Truffle",         desc: "The only thing missing is the heart-shaped box it came in." },
            { name: "Ginger Snap",               desc: "Simple and refreshing ginger with a bubbly sensation." },
            { name: "Bee Sting",                 desc: "Supercharged margarita-tini with a green chili-infused tequila." },
            { name: "Jimmy Hendricks",           desc: "Light and lemony fun for gin lovers with a touch of basil." },
            { name: "Raztini",                   desc: "Plain and simply, raspberry." },
            { name: "Canadian Cowboy",           desc: "Good ol\u2019 Canadian whiskey and a cherry sidekick." },
            { name: "Manhattan",                 desc: "Bourbon with a hint of cherry." },
            { name: "Rob Roy",                   desc: "A Manhattan for scotch drinkers." },
            { name: "Gibson",                    desc: "Gin with pearl onions." },
            { name: "Vesper",                    desc: "Do you love gin and vodka together with a touch of lemon?" },
            { name: "Down and Dirty",            desc: "Your basic martini \u2014 choose from well or our grand variety of top shelf vodkas." },
            { name: "Dirty Dill",                desc: "Dirty martini with a pickle." },
            { name: "Cosmo",                     desc: "Sex and the City favorite." },
            { name: "Pomatini",                  desc: "Simply pomegranate." },
            { name: "Lemondrop",                 desc: "Oh the heavenly lemon." },
            { name: "Bar Ten Dragon",            desc: "Jason\u2019s signature Bar Ten specialty." },
            { name: "French Martini",            desc: "Vodka with a sweeter kiss." },
            { name: "White Flower",              desc: "Pure and refreshing." },
            { name: "Peartini",                  desc: "This was picked for you." },
          ],
        },
        {
          label: "Cocktails",
          items: [
            { name: "Grapefruit Basil Lime Aid" },
            { name: "Dirty Girl Lemonade",  desc: "From one dirty girl to another." },
            { name: "Bikini Drink",         desc: "Straight off the island." },
            { name: "Dark & Stormy",        desc: "Ride this storm out with dark rum and ginger beer." },
            { name: "Gin Fizz" },
            { name: "Mojito" },
            { name: "Raspberry Mojito" },
            { name: "Moscow Mule",          desc: "Sneaking past you with house vodka and ginger beer." },
            { name: "Old Fashioned",        desc: "If you don\u2019t know, ask your grandpa." },
            { name: "Mint Julep",           desc: "If you have your derby hat, we have your tin cup." },
          ],
        },
        {
          label: "Margaritas",
          items: [
            { name: "Basic Margarita",         desc: "100 A\u00f1os Souza Reposado and Grand Gala made with fresh squeezed limes and fresh sour." },
            { name: "Bar Ten Margarita",       desc: "Don Julio, Cointreau, fresh squeezed lime, and water." },
            { name: "Patron Margarita",        desc: "Patron Silver with Citronage made with fresh squeezed limes and fresh sour." },
            { name: "Grapefruit Margarita",    desc: "Corazon and St. Germain made with fresh squeezed limes and fresh sour." },
            { name: "Slick Black Cadillac",    desc: "Made with Don Julio and topped with Wyoming-made Koltiska, fresh squeezed limes and fresh sour." },
            { name: "Pomegranate Margarita",   desc: "Corralejo and Grand Marnier made with fresh squeezed limes and fresh sour." },
          ],
        },
        {
          label: "After Dinner Drinks",
          items: [
            { name: "Brandy Alexander" },
            { name: "B-52" },
            { name: "Mudslide" },
            { name: "White Russian" },
            { name: "Black Russian" },
            { name: "Smith & Kearns" },
            { name: "Colorado Bulldog" },
            { name: "Dirty Girlscout" },
          ],
        },
        {
          label: "Hot Drinks",
          items: [
            { name: "Hot Apple Pie" },
            { name: "Banana Fosters" },
            { name: "Nutty Irishman" },
            { name: "Hot Orange" },
            { name: "Toasty Almond" },
          ],
        },
        {
          label: "Local Breweries on Tap",
          items: [
            { name: "Grand Teton Brewing Co" },
            { name: "New Belgium Brewing" },
            { name: "Altitude" },
            { name: "Wind River Brewing Co" },
            { name: "Snake River Brewing" },
            { name: "Library" },
            { name: "Thai Me Up" },
            { name: "Lander Brewing Co" },
          ],
        },
        {
          label: "Domestic",
          items: [
            { name: "Budweiser" },
            { name: "Coors Original" },
          ],
        },
        {
          label: "Light Beer",
          items: [
            { name: "Bud Light" },
            { name: "Coors Light" },
            { name: "Miller Lite" },
            { name: "MGD 64" },
          ],
        },
        {
          label: "Imports",
          items: [
            { name: "Corona" },
            { name: "Guinness" },
            { name: "Red Stripe" },
            { name: "Stella Artois" },
            { name: "Newcastle" },
            { name: "Boddingtons Pub Ale" },
          ],
        },
        {
          label: "Craft & Regional",
          items: [
            { name: "Sam Adams" },
            { name: "Sessions" },
            { name: "Shiner Bock" },
            { name: "Deschutes" },
            { name: "Bayern" },
            { name: "Wind River Brewery" },
            { name: "Sierra Nevada" },
            { name: "Mirror Pond" },
            { name: "Odell" },
            { name: "New Belgium" },
            { name: "Oskar Blues" },
          ],
        },
        {
          label: "Non-Alcoholic",
          items: [
            { name: "Kaliber", desc: "Non-alcoholic beer by Guinness." },
          ],
        },
      ],
      footer: "Pricing and daily specials vary. Ask your bartender for current selections and features.",
    },
    catering: {
      cateringNote: "We are now able to cater your big events. Everything is made from scratch with fresh ingredients. We also offer top-shelf bar service. See server for details and application.",
      hoursRegular: "4 PM \u2013 Close, Monday \u2013 Saturday",
      kitchenMonThu: "Monday \u2013 Thursday: Kitchen open till 10 PM",
      kitchenFriSat: "Friday & Saturday: Kitchen open till 11 PM",
    },
  },
  featuredItems: [
    {
      name: "Stuffed Mushrooms",
      description: "A local favorite from the appetizer menu. Rich, satisfying, and worth starting with.",
      emoji: "🍄",
      image: "images/stuffed-mushrooms.jpg",
    },
    {
      name: "Whiskey BBQ Sliders",
      description: "Tender, smoky, and built for sharing over a cold drink.",
      emoji: "🍔",
      image: "images/whiskey-bbq-sliders.jpg",
    },
    {
      name: "Pork Street Tacos",
      description: "Street-style and packed with flavor. A crowd favorite.",
      emoji: "🌮",
      image: "images/pork-street-tacos.jpg",
    },
    {
      name: "Meatball Sliders",
      description: "Hearty sliders that hit the spot before or after a round.",
      emoji: "🍝",
      image: "images/meatball-sliders.jpg",
    },
    {
      name: "Chicken Pot Pie",
      description: "Comfort food done right — warm and filling.",
      emoji: "🥧",
      image: "images/chicken-pot-pie.jpg",
    },
  ],
  events: [
    {
      title: "Trivia Night",
      day: "Thursday",
      time: "7:00 PM",
      description:
        "Test your knowledge every Thursday. Bring a team, grab a round, and compete for bragging rights in Riverton's best trivia night.",
      recurring: true,
      icon: "🎯",
    },
    {
      title: "Live Music",
      day: "Fridays & Saturdays",
      time: "Varies",
      description:
        "Local and regional acts take the stage on weekend nights. Call ahead or check our social pages for the current lineup.",
      recurring: true,
      icon: "🎸",
    },
    {
      title: "Special Events",
      day: "Rotating",
      time: "Varies",
      description:
        "Private parties, holiday events, and one-off specials throughout the year. Call us to reserve space or ask about upcoming dates.",
      recurring: false,
      icon: "🥂",
    },
  ],
};
